#!/usr/bin/python

import sys
import time
import httplib
import urllib2
import base64
import argparse
import simplejson as json
from datetime import timedelta
from pprint import pprint
import traceback


#HOST = "ec2-184-169-213-66.us-west-1.compute.amazonaws.com"
#PORT = 50003
HOST = "restapi.pigeonmtk.twbbs.org"
PORT = 80


def get_service_info(service_id, username, password, verbose):
    try:
        conn = httplib.HTTPConnection(host=HOST, port=PORT)

        if verbose: conn.set_debuglevel(1)

        headers = {}
        base64string = base64.encodestring('%s:%s' % (username, password)).replace('\n', '')
        headers = {'Authorization': 'Basic ' + base64string}

        conn.request('GET', "/service/" + service_id, headers=headers)
        resp = conn.getresponse()
        body = resp.read()

    except Exception as e:
        traceback.print_exc(file=sys.stdout)
        raise Exception('Connection Error: %s' % e)
    finally:
        conn.close()

    if resp.status >= 400:
        raise ValueError('Response Error: %s, %s' % (resp.status, resp.reason))
    return json.loads(body)


parser = argparse.ArgumentParser(description='Query the properties of a service')
parser.add_argument('service', help='Service identification')
parser.add_argument('--key', help='Developer key for authentication', required=True)
parser.add_argument('--secret', help='Developer secret for authentication', required=True)
parser.add_argument('-v','--verbose', help='Print debug message', action='store_true')
args = vars(parser.parse_args())


resp = get_service_info(service_id=args['service'], username=args['key'], password=args['secret'], verbose=args['verbose'])
print json.dumps(resp, indent=4)
